### ISSUE TITLE
How to add Info Box

### ISSUE THREAD

**Issue by Arqu** [rtsinani/PinClusterer#4]
Is there any way to provide a handler to launch an info box when one of the markers is clicked?

**Comment by mirko77** [comment]
@rtsinani how do I identify which pushpin was clicked? I have info attached to each location, but I have not find a way to attach an ID to each pushpin and get it back

**Comment by rtsinani** [comment]
You can do that using events in `onClusterToMap` callback. There you can also extend the pushpins with ids or other properties you need.
