### ISSUE TITLE
tiles load issue

### ISSUE THREAD

**Issue by revolunet** [rtsinani/PinClusterer#5]
looks like you have the same tiles load issue as we experienced :

![capture decran 2014-03-18 a 18 01 05](https://f.cloud.github.com/assets/124937/2450795/f10a6920-aebe-11e3-9321-1e74b5a7782b.png)

Looks like theres an issue when the map is initially hidden :

Here's how we fixed it :
```js
MM.Events.addHandler(map, 'viewchangeend', function() {
    if (map.getWidth()===1 && map.getHeight()===1) {
        map.setOptions({
            height: '100%',
            width: '100%'
        });
    }
});
```

Hope this helps

**Comment by rtsinani** [comment]
That looks like a connection issue to me.
