### ISSUE TITLE
different id for every pin

### ISSUE THREAD

**Issue by jibrilrian** [rtsinani/PinClusterer#8]
i love your library but i wonder how do i add id for every pin? cause now the id is null (<a id="null" ....), i want to add different class for some pins too but i don't know how to do it,

sorry if my questions so noob

**Comment by rtsinani** [comment]
If you have a look at this [example](https://github.com/rtsinani/PinClusterer/blob/master/examples/infobox.html), you may use the `onClusterToMap` callback to manipulate the `pushpin` object exposed.

**Comment by jibrilrian** [comment]
thanks, it's done
